export const hiragana = [
    {
        character: 'あ',
        romaji: 'a',
        row: 1,
        rowName: 'v',
        frequency: 100,
        vowelGroup: 'a',
    },
    {
        character: 'い',
        romaji: 'i',
        row: 1,
        rowName: 'v',
        frequency: 90,
        vowelGroup: 'i',
    },
    {
        character: 'う',
        romaji: 'u',
        row: 1,
        rowName: 'v',
        frequency: 80,
        vowelGroup: 'u',
    },
    {
        character: 'え',
        romaji: 'e',
        row: 1,
        rowName: 'v',
        frequency: 70,
        vowelGroup: 'e',
    },
    {
        character: 'お',
        romaji: 'o',
        row: 1,
        rowName: 'v',
        frequency: 60,
        vowelGroup: 'o',
    },
    {
        character: 'か',
        romaji: 'ka',
        row: 2,
        rowName: 'k',
        frequency: 95,
        vowelGroup: 'a',
    },
    {
        character: 'き',
        romaji: 'ki',
        row: 2,
        rowName: 'k',
        frequency: 85,
        vowelGroup: 'i',
    },
    {
        character: 'く',
        romaji: 'ku',
        row: 2,
        rowName: 'k',
        frequency: 75,
        vowelGroup: 'u',
    },
    {
        character: 'け',
        romaji: 'ke',
        row: 2,
        rowName: 'k',
        frequency: 65,
        vowelGroup: 'e',
    },
    {
        character: 'こ',
        romaji: 'ko',
        row: 2,
        rowName: 'k',
        frequency: 55,
        vowelGroup: 'o',
    },
    {
        character: 'さ',
        romaji: 'sa',
        row: 3,
        rowName: 's',
        frequency: 90,
        vowelGroup: 'a',
    },
    {
        character: 'し',
        romaji: 'shi',
        row: 3,
        rowName: 's',
        frequency: 80,
        vowelGroup: 'i',
    },
    {
        character: 'す',
        romaji: 'su',
        row: 3,
        rowName: 's',
        frequency: 70,
        vowelGroup: 'u',
    },
    {
        character: 'せ',
        romaji: 'se',
        row: 3,
        rowName: 's',
        frequency: 60,
        vowelGroup: 'e',
    },
    {
        character: 'そ',
        romaji: 'so',
        row: 3,
        rowName: 's',
        frequency: 50,
        vowelGroup: 'o',
    },
    {
        character: 'た',
        romaji: 'ta',
        row: 4,
        rowName: 't',
        frequency: 95,
        vowelGroup: 'a',
    },
    {
        character: 'ち',
        romaji: 'chi',
        row: 4,
        rowName: 't',
        frequency: 85,
        vowelGroup: 'i',
    },
    {
        character: 'つ',
        romaji: 'tsu',
        row: 4,
        rowName: 't',
        frequency: 75,
        vowelGroup: 'u',
    },
    {
        character: 'て',
        romaji: 'te',
        row: 4,
        rowName: 't',
        frequency: 65,
        vowelGroup: 'e',
    },
    {
        character: 'と',
        romaji: 'to',
        row: 4,
        rowName: 't',
        frequency: 55,
        vowelGroup: 'o',
    },
    {
        character: 'な',
        romaji: 'na',
        row: 5,
        rowName: 'n',
        frequency: 90,
        vowelGroup: 'a',
    },
    {
        character: 'に',
        romaji: 'ni',
        row: 5,
        rowName: 'n',
        frequency: 80,
        vowelGroup: 'i',
    },
    {
        character: 'ぬ',
        romaji: 'nu',
        row: 5,
        rowName: 'n',
        frequency: 70,
        vowelGroup: 'u',
    },
    {
        character: 'ね',
        romaji: 'ne',
        row: 5,
        rowName: 'n',
        frequency: 60,
        vowelGroup: 'e',
    },
    {
        character: 'の',
        romaji: 'no',
        row: 5,
        rowName: 'n',
        frequency: 50,
        vowelGroup: 'o',
    },
    {
        character: 'は',
        romaji: 'ha',
        row: 6,
        rowName: 'h',
        frequency: 95,
        vowelGroup: 'a',
    },
    {
        character: 'ひ',
        romaji: 'hi',
        row: 6,
        rowName: 'h',
        frequency: 85,
        vowelGroup: 'i',
    },
    {
        character: 'ふ',
        romaji: 'fu',
        row: 6,
        rowName: 'h',
        frequency: 75,
        vowelGroup: 'u',
    },
    {
        character: 'へ',
        romaji: 'he',
        row: 6,
        rowName: 'h',
        frequency: 65,
        vowelGroup: 'e',
    },
    {
        character: 'ほ',
        romaji: 'ho',
        row: 6,
        rowName: 'h',
        frequency: 55,
        vowelGroup: 'o',
    },
    {
        character: 'ま',
        romaji: 'ma',
        row: 7,
        rowName: 'm',
        frequency: 90,
        vowelGroup: 'a',
    },
    {
        character: 'み',
        romaji: 'mi',
        row: 7,
        rowName: 'm',
        frequency: 80,
        vowelGroup: 'i',
    },
    {
        character: 'む',
        romaji: 'mu',
        row: 7,
        rowName: 'm',
        frequency: 70,
        vowelGroup: 'u',
    },
    {
        character: 'め',
        romaji: 'me',
        row: 7,
        rowName: 'm',
        frequency: 60,
        vowelGroup: 'e',
    },
    {
        character: 'も',
        romaji: 'mo',
        row: 7,
        rowName: 'm',
        frequency: 50,
        vowelGroup: 'o',
    },
    {
        character: 'や',
        romaji: 'ya',
        row: 8,
        rowName: 'y',
        frequency: 80,
        vowelGroup: 'a',
    },
    {
        character: 'ゆ',
        romaji: 'yu',
        row: 8,
        rowName: 'y',
        frequency: 70,
        vowelGroup: 'u',
    },
    {
        character: 'よ',
        romaji: 'yo',
        row: 8,
        rowName: 'y',
        frequency: 60,
        vowelGroup: 'o',
    },
    {
        character: 'ら',
        romaji: 'ra',
        row: 9,
        rowName: 'r',
        frequency: 85,
        vowelGroup: 'a',
    },
    {
        character: 'り',
        romaji: 'ri',
        row: 9,
        rowName: 'r',
        frequency: 75,
        vowelGroup: 'i',
    },
    {
        character: 'る',
        romaji: 'ru',
        row: 9,
        rowName: 'r',
        frequency: 65,
        vowelGroup: 'u',
    },
    {
        character: 'れ',
        romaji: 're',
        row: 9,
        rowName: 'r',
        frequency: 55,
        vowelGroup: 'e',
    },
    {
        character: 'ろ',
        romaji: 'ro',
        row: 9,
        rowName: 'r',
        frequency: 45,
        vowelGroup: 'o',
    },
    {
        character: 'わ',
        romaji: 'wa',
        row: 10,
        rowName: 'w',
        frequency: 70,
        vowelGroup: 'a',
    },
    {
        character: 'を',
        romaji: 'wo',
        row: 10,
        rowName: 'w',
        frequency: 60,
        vowelGroup: 'o',
    },
    {
        character: 'ん',
        romaji: 'n',
        row: 10,
        rowName: 'n',
        frequency: 40,
        vowelGroup: 'n',
    },
];
