version: '3.1'
services:
    mongo:
        build: ./mongodb_rs
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: testpass
            MONGO_INITDB_DATABASE: sensei #TODO: Use secrets 
            MONGO_REPLICA_HOST: localhost
            MONGO_REPLICA_PORT: 27017
        ports:
            - '27017:27017'
